on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

  -steps:
    -name: checkout repository
    uses: actions/checkout@v4

    -name: log-into-docker
    uses: docker/login-actions@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

    -name: build docker images
    run: |
      docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-website:v1 .

    -name: push docker images
    run: |
      docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-website:v1

    -name: success message
    run: |
      echo " docker images is build successfully and pushed into the dockerhub "

